//admin
export const FETCH_ALL_ADMIN_REQUEST = "FETCH_ALL_ADMIN_REQUEST"
export const FETCH_ALL_ADMIN_FAIL = "FETCH_ALL_ADMIN_FAIL"
export const FETCH_ALL_ADMIN_SUCCESS = "FETCH_ALL_ADMIN_SUCCESS"

export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS"
export const DELETE_ADMIN_START = "DELETE_ADMIN_START"
export const DELETE_ADMIN_FAIL = "DELETE_ADMIN_FAIL"

export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS"
export const UPDATE_ADMIN_START = "UPDATE_ADMIN_START"
export const UPDATE_ADMIN_FAIL = "UPDATE_ADMIN_FAIL"

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"
export const ADMIN_LOGOUT = "ADMIN_LOGOUT "

export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST"
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS"
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL"
export const ADMIN_DETAILS_RESET = "ADMIN_DETAILS_RESET"

//user
export const FETCH_ALL_USER_REQUEST = "FETCH_ALL_USER_REQUEST"
export const FETCH_ALL_USER_FAIL = "FETCH_ALL_USER_FAIL"
export const FETCH_ALL_USER_SUCCESS = "FETCH_ALL_USER_SUCCESS"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_START = "DELETE_USER_START"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_START = "UPDATE_USER_START"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

//designer
export const FETCH_ALL_DESIGNER_REQUEST = "FETCH_ALL_DESIGNER_REQUEST"
export const FETCH_ALL_DESIGNER_FAIL = "FETCH_ALL_DESIGNER_FAIL"
export const FETCH_ALL_DESIGNER_SUCCESS = "FETCH_ALL_DESIGNER_SUCCESS"

export const DELETE_DESIGNER_SUCCESS = "DELETE_DESIGNER_SUCCESS"
export const DELETE_DESIGNER_START = "DELETE_DESIGNER_START"
export const DELETE_DESIGNER_FAIL = "DELETE_DESIGNER_FAIL"

export const UPDATE_DESIGNER_SUCCESS = "UPDATE_DESIGNER_SUCCESS"
export const UPDATE_DESIGNER_START = "UPDATE_DESIGNER_START"
export const UPDATE_DESIGNER_FAIL = "UPDATE_DESIGNER_FAIL"

export const FETCH_RATED_DESIGNERS_REQUEST = "FETCH_RATED_DESIGNERS_REQUEST"
export const FETCH_RATED_DESIGNERS_FAIL = "FETCH_RATED_DESIGNERS_FAIL"
export const FETCH_RATED_DESIGNERS_SUCCESS = "FETCH_RATED_DESIGNERS_SUCCESS"
