export const FETCH_ALL_ADMIN_REQUEST = "FETCH_ALL_ADMIN_REQUEST"
export const FETCH_ALL_ADMIN_FAIL = "FETCH_ALL_ADMIN_FAIL"
export const FETCH_ALL_ADMIN_SUCCESS = "FETCH_ALL_ADMIN_SUCCESS"

export const FETCH_ALL_USER_REQUEST = "FETCH_ALL_USER_REQUEST"
export const FETCH_ALL_USER_FAIL = "FETCH_ALL_USER_FAIL"
export const FETCH_ALL_USER_SUCCESS = "FETCH_ALL_USER_SUCCESS"

export const FETCH_ALL_DESIGNER_REQUEST = "FETCH_ALL_DESIGNER_REQUEST"
export const FETCH_ALL_DESIGNER_FAIL = "FETCH_ALL_DESIGNER_FAIL"
export const FETCH_ALL_DESIGNER_SUCCESS = "FETCH_ALL_DESIGNER_SUCCESS"
