export const CREATE_SHOP_REQUEST = "CREATE_SHOP_REQUEST"
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS"
export const CREATE_SHOP_FAIL = "CREATE_SHOP_FAIL"
export const CREATE_SHOP_RESET = "CREATE_SHOP_RESET"

export const REGISTER_DESIGNER_REQUEST = "REGISTER_DESIGNER_REQUEST"
export const REGISTER_DESIGNER_SUCCESS = "REGISTER_DESIGNER_SUCCESS"
export const REGISTER_DESIGNER_FAIL = "REGISTER_DESIGNER_FAIL"
export const REGISTER_DESIGNER_RESET = "REGISTER_DESIGNER_RESET"
