export const CREATE_SHOP_REQUEST = "CREATE_SHOP_REQUEST"
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS"
export const CREATE_SHOP_FAIL = "CREATE_SHOP_FAIL"
export const CREATE_SHOP_RESET = "CREATE_SHOP_RESET"

export const REGISTER_DESIGNER_REQUEST = "REGISTER_DESIGNER_REQUEST"
export const REGISTER_DESIGNER_SUCCESS = "REGISTER_DESIGNER_SUCCESS"
export const REGISTER_DESIGNER_FAIL = "REGISTER_DESIGNER_FAIL"
export const REGISTER_DESIGNER_RESET = "REGISTER_DESIGNER_RESET"

export const FETCH_DESIGNER_PRODUCT_REQUEST = "FETCH_DESIGNER_PRODUCT_REQUEST"
export const FETCH_DESIGNER_PRODUCT_SUCCESS = "FETCH_DESIGNER_PRODUCT_SUCCESS"
export const FETCH_DESIGNER_PRODUCT_FAIL = "FETCH_DESIGNER_PRODUCT_FAIL"
export const FETCH_DESIGNER_PRODUCT_RESET = "FETCH_DESIGNER_PRODUCT_RESET"

export const TOP_DESIGNERS_REQUEST = "TOP_DESIGNERS_REQUEST"
export const TOP_DESIGNERS_SUCCESS = "TOP_DESIGNERS_SUCCESS"
export const TOP_DESIGNERS_FAIL = "TOP_DESIGNERS_FAIL"
export const TOP_DESIGNERS_RESET = "FETCH_DESIGNERS_RESET"

export const GET_DESIGNER_BY_ID_REQUEST = "GET_DESIGNER_BY_ID_REQUEST"
export const GET_DESIGNER_BY_ID_SUCCESS = "GET_DESIGNER_BY_ID_SUCCESS"
export const GET_DESIGNER_BY_ID_FAIL = "GET_DESIGNER_BY_ID_FAIL"

export const DESIGNER_PRODUCT_DATA_REQUEST = "DESIGNER_PRODUCT_DATA_REQUEST"
export const DESIGNER_PRODUCT_DATA_SUCCESS = "DESIGNER_PRODUCT_DATA_SUCCESS"
export const DESIGNER_PRODUCT_DATA_RESET = "DESIGNER_PRODUCT_DATA_RESET"

export const DESIGNER_PRODUCT_DATA_FAIL = "DESIGNER_PRODUCT_DATA_FAIL"
