// Get All Products
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"

// add a Products
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"

//Get Single Product Through ID
export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST"
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL"
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS"

//delete a product
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START"
export const DELETE_PRODUCT_FAIL = "DELETE_DESIGNER_FAIL"
