// Get All Products
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";

//Get Single Product Through ID
export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
